name: Daily Build Trigger

on:
  schedule:
    # Daylight savings (AEDT, UTC+11) → 8 AM Sydney = 21:00 UTC previous day
    - cron: '0 21 * * 10-12'  # Oct–Dec
    - cron: '0 21 * * 1-3'    # Jan–Mar
    # Standard time (AEST, UTC+10) → 8 AM Sydney = 22:00 UTC previous day
    - cron: '0 22 * * 4-9'    # Apr–Sep
  workflow_dispatch:           # Optional manual trigger

jobs:
  call-build:
    uses: ./.github/workflows/build.yml
    with:
      from_ci: true
