name: Daily 5am Sydney Build

on:
  schedule:
    # Cover both DST states (AEDT and AEST); we’ll gate to 05:00 local time below
    - cron: '0 18 * * *'  # 05:00 AEDT (UTC+11)
    - cron: '0 19 * * *'  # 05:00 AEST (UTC+10)
  workflow_dispatch:

jobs:
  gate:
    runs-on: ubuntu-latest
    outputs:
      run: ${{ steps.gate.outputs.run }}
    steps:
      - name: Gate to only run at 05:00 Australia/Sydney (or always for manual)
        id: gate
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "Manual dispatch - allowing run"
            echo "run=true" >> $GITHUB_OUTPUT
            exit 0
          fi

          export TZ=Australia/Sydney
          NOW="$(date +%H:%M)"
          echo "Local time in Australia/Sydney: $NOW"
          if [ "$NOW" = "05:00" ]; then
            echo "run=true" >> $GITHUB_OUTPUT
          else
            echo "run=false" >> $GITHUB_OUTPUT
          fi

  run-build:
    needs: gate
    if: needs.gate.outputs.run == 'true'
    uses: ./.github/workflows/build.yml
    with:
      from_ci: true
